retrieval_task:
  description: >
    Execute a vector search in the database to retrieve up to 5 bullet points of the most relevant information about the Wizerly application.
  expected_output: >
    A list with 5 bullet points showing similarity scores and text snippets related to the Wizerly application. If no relevant data is found, respond with "I couldn't find anything."
  agent: researcher


# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
